name: carelink
description: "App for care"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # 상태 관리
  provider: ^6.1.2

  # 의존성 주입
  get_it: ^7.6.0

  # Firebase 패키지
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1

  # 이미지 선택
  image_picker: ^1.1.2

  # WebRTC
  flutter_webrtc: ^0.11.7

  # 백그라운드 서비스
  flutter_background_service: ^5.0.10

  # 라우팅
  go_router: ^14.2.7

  # 로컬 알림
  flutter_local_notifications: ^17.2.3

  # 권한 요청
  permission_handler: ^11.1.0

  # 로컬 스토리지
  shared_preferences: ^2.3.2

  # 쿠퍼티노 iOS icon
  cupertino_icons: ^1.0.8

dev_dependencies:
  # delete
  change_app_package_name: ^1.4.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

